/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,js}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "surface-container-low": "#151b2d",
        "on-error": "#690005",
        "on-primary": "#00363d",
        "on-primary-fixed": "#001f24",
        error: "#ffb4ab",
        "on-surface": "#dce1fb",
        "on-tertiary-fixed-variant": "#3a485c",
        "surface-variant": "#2e3447",
        "outline-variant": "#3b494c",
        "tertiary-fixed": "#d5e3fd",
        "on-surface-variant": "#bac9cc",
        surface: "#0c1324",
        "surface-tint": "#00daf3",
        "on-tertiary": "#233144",
        outline: "#849396",
        "on-tertiary-fixed": "#0d1c2f",
        "on-secondary-fixed": "#131b2e",
        "on-background": "#dce1fb",
        primary: "#c3f5ff",
        "on-primary-fixed-variant": "#004f58",
        "primary-container": "#00e5ff",
        "tertiary-container": "#c3d1ea",
        "surface-dim": "#0c1324",
        "error-container": "#93000a",
        "on-secondary": "#283044",
        "inverse-primary": "#006875",
        "inverse-on-surface": "#2a3043",
        "surface-bright": "#33394c",
        secondary: "#bec6e0",
        "surface-container": "#191f31",
        "surface-container-highest": "#2e3447",
        "secondary-container": "#3f465c",
        background: "#0c1324",
        "tertiary-fixed-dim": "#b9c7e0",
        "on-tertiary-container": "#4c5a6f",
        "on-secondary-container": "#adb4ce",
        "secondary-fixed-dim": "#bec6e0",
        "secondary-fixed": "#dae2fd",
        tertiary: "#e4edff",
        "on-primary-container": "#00626e",
        "primary-fixed-dim": "#00daf3",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-container-high": "#23293c",
        "inverse-surface": "#dce1fb",
        "surface-container-lowest": "#070d1f",
        "primary-fixed": "#9cf0ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        gutter: "24px",
        "margin-desktop": "64px",
        base: "8px",
        "nav-height": "80px",
        "container-max": "1280px",
        "margin-tablet": "32px",
      },
      fontFamily: {
        "headline-xl": ["Hanken Grotesk"],
        "body-md": ["Geist"],
        "headline-md": ["Hanken Grotesk"],
        "label-sm": ["Geist"],
        "label-md": ["Geist"],
        "headline-sm": ["Hanken Grotesk"],
        "body-lg": ["Geist"],
        "body-sm": ["Geist"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-xl-mobile": ["Hanken Grotesk"],
      },
      fontSize: {
        "headline-xl": [
          "60px",
          {
            lineHeight: "72px",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": [
          "32px",
          { lineHeight: "40px", fontWeight: "700" },
        ],
        "label-sm": [
          "12px",
          {
            lineHeight: "14px",
            letterSpacing: "0.05em",
            fontWeight: "500",
          },
        ],
        "label-md": [
          "14px",
          {
            lineHeight: "16px",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        "headline-sm": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "headline-xl-mobile": [
          "40px",
          {
            lineHeight: "48px",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
      },
      animation: {
        "pulse-fast": "pulse 1.5s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in-up": "fadeInUp 0.8s ease-out forwards",
        "scan-line": "scan 4s linear infinite",
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(40px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scan: {
          "0%": { transform: "translateY(-100%)" },
          "100%": { transform: "translateY(400%)" },
        },
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
